name: automerge
on:
  pull_request:
    types: [labeled, opened, reopened, synchronize]
permissions:
  contents: write
  pull-requests: write
jobs:
  automerge:
    if: contains(join(github.event.pull_request.labels.*.name, ','), 'automerge')
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          UPDATE_METHOD: rebase
          REQUIRED_LABELS: automerge
